# Copyright (c) 2021-2023 Ted WU <wulited@outlook.com>

site_name: Ronin's Notes
site_url: https://execution.icu
site_author: ronin
site_description: >-
  Your attitude, not your aptitude, will determine your altitude.

# copyright: Copyright &copy; 2018-2023 Ronin

nav:
  - Home: index.md

  - Arts:
    - arts/wukong.md
    - arts/cook.md

  - Tools:
      - tools/gfw.md
      - tools/ffmpeg.md
      - tools/wine.md
      - tools/searxng.md
      - tools/agent.md

  - Computer Science:
    - Python:
      - Flask:
        - cs/python/flask/1.0.md
    - Java:
      - Basics:
        - cs/java/basics/concept.md
        - cs/java/basics/2024.s1.md
        - cs/java/basics/t1.md
        - cs/java/basics/t2.md
        - cs/java/basics/w4.md
        - cs/java/basics/w5.md
        - cs/java/basics/w6.md
        - cs/java/basics/w7.md
        - cs/java/basics/w8.md
        - cs/java/basics/w9.md
        - cs/java/basics/w10.md
    - Networks:
      - 3002:
        - cs/network/w1.md
        - cs/network/w2.md
        - cs/network/w3.md
        - cs/network/w4.md
        - cs/network/w5.md
        - cs/network/w6.md
        - cs/network/w7.md
        - cs/network/w8.md
        - cs/network/w9.md
        - cs/network/w10.md
        - cs/network/w11.md

    - MERN:
      - HTML:
        - cs/mern/html/html_syntax.md
      - 3403:
        - cs/mern/3403/2024.md
        - cs/mern/3403/l1.md
        - cs/mern/3403/l2.md
        - cs/mern/3403/l3.md
        - cs/mern/3403/l4.md
        - cs/mern/3403/l5.md
        - cs/mern/3403/l5_ex.md
        - cs/mern/3403/l6.md
        - cs/mern/3403/l6_ex.md
        - cs/mern/3403/l7.md
        - cs/mern/3403/l8.md
        - cs/mern/3403/l9.md
        - cs/mern/3403/l10.md
        - cs/mern/3403/l11.md
        - cs/mern/3403/l12.md
        - cs/mern/3403/l13.md
        - cs/mern/3403/l14.md
        - cs/mern/3403/l15.md

    - Operating Systems:
      - C System Programming:
        - cs/c/2.1.md
        - cs/c/2.2.md
        - cs/c/2.3.md
        - cs/c/2.4.md
        - cs/c/3.1.md
        - cs/c/3.2.md
        - cs/c/3.3.md
        - cs/c/4.1.md
        - cs/c/4.2.md
        - cs/c/4.3.md
        - cs/c/5.1.md
        - cs/c/5.2.md

  - Handbooks:
    - Telegram:
      - handbook/telegram.md
    - Computer Science Plan:
      - handbook/csplan.md
      
  - Cybersecurity:
    - cyber/networkattack.md

theme:
  name: material
  # custom_dir: overrides
  favicon: resources/icon.svg
  logo: resources/logo.svg
  font: 
    code: JetBrains Mono

  language: zh
  features:
    - navigation.instant # 启用即时导航，提高页面切换速度
    - navigation.instant.prefetch # 预取链接，进一步提升性能
    - navigation.instant.progress # 显示加载进度
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    - navigation.top
    - navigation.footer # display prev/next links
    - content.code.annotate
    - content.code.copy
  
  palette:
    - scheme: default
      primary: blue grey
      
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      
      toggle:
        icon: material/weather-night
        name: Switch to light mode



markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  # - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc
  - mdx_truly_sane_lists:
      nested_indent: 4

plugins:
  - tags
  - search:
      separator: '[\s\-\.,;:\(\)\[\]{}\/\\]+' # 改进搜索分词，支持更多分隔符
      lang: zh
  - minify: # 启用压缩
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
      css_files:
        - resources/extra.css
      js_files:
        - resources/katex.js

# search_index_only: false

# 构建优化
strict: true # 严格模式，确保所有链接有效
use_directory_urls: true # 使用目录风格的 URL

# 性能优化
extra: {}
#   homepage: https://herointene.github.io
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/herointene
#       name: Github
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/wyndkatbcis
#       name: Twitter
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/tedilitarianism/
#       name: Instagram
#     - icon: fontawesome/brands/soundcloud
#       link: https://soundcloud.com/wulited
#       name: SoundCloud
#     - icon: fontawesome/solid/paper-plane
#       link: mailto:<ted@ewig.dev>
#       name: Email me
#   analytics:
#     provider: google
#     property: G-XXXXXX
extra_css:
  - resources/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - resources/katex.js