name: Build MkDocs Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'resources/**'
      - '.github/workflows/**'
      - 'requirements.txt'
  
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'resources/**'
      - '.github/workflows/**'
      - 'requirements.txt'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Cache pip dependencies  
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build documentation
      run: |
        mkdocs build --verbose
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mkdocs-site
        path: site/
        retention-days: 30
